### PR TITLE
Update LLVM branch to latest

### PR DESCRIPTION
**Pull request by yuki-js**

### CODE REVIEW

**Comment by yuki-js** [comment]
[clabot:check]

**Comment by TriplEight** [comment]
Hi, can you provide us with any explanation why it should be updated? Does it even work with this version?

**Comment by yuki-js** [comment]
LLVM branch name seems to be changed so cloning failed.
I could successfully compile it after changing it.

dockerfile: https://github.com/my-number/mynachain/blob/master/Dockerfile.arm
image: https://github.com/my-number/mynachain/packages/280247

**Comment by TriplEight** [comment]
Seems [legit](https://github.com/rust-lang/rust/pull/67759/files). Thank you, @yuki-js for the contribution!

**Pull request merged**
