### PR TITLE
docker container build with redis_exporter

### PR DESCRIPTION
**Pull request by gabreal**
deployment suggestion: https://mehmandarov.com/start-docker-containers-automatically/ running it inside docker with systemd.

### CODE REVIEW

**Comment by lovelaced** [comment]
Thanks for this! Building in a docker image seems pretty easy and convenient. Out of curiosity, why not just rely on the docker daemon to autostart the image: https://docs.docker.com/config/containers/start-containers-automatically/
I found some gotchas about using systemd to control running docker containers in this post, but it is a bit "old" in terms of docker maturity: https://blog.container-solutions.com/running-docker-containers-with-systemd

**Comment by gabreal** [comment]
@lovelaced  thanks for the links. My initial thoughts were that systemd would be more transparent and mature in handling system level jobs. Also that you would not have a dependency to think of anything when restarting the docker daemon. But another good argument from the article above:

> Using systemd or an equivalent is particularly useful if you have another, possibly non-containerized service that is dependent on the container.

But I guess I would prefer to run it via systemd even when running containerized redis, or would it be possible to declare dependencies in docker?

**Comment by TriplEight** [comment]
:+1:

**Comment by gabreal** [comment]
That's the deployment: https://gitlab.parity.io/parity/devops/merge_requests/45

**Pull request merged**
