### PR TITLE
Android dockerfile update

### PR DESCRIPTION
**Pull request by TriplEight**
- smaller
- optimized
- with cache

### CODE REVIEW

**Comment by tomaka** [comment]
The indentation is inconsistent and there are commented out lines of code, but looks good other than that.

**Comment by TriplEight** [comment]
> The indentation is inconsistent and there are commented out lines of code, but looks good other than that.

Indentation shows related commands like installations and ripped long commands.
Commented code is to understand where it's needed, to navigate in this wild.
Looks better than before, but this build environment is insane, would be very happy to make it simpler.

**Comment by tomaka** [comment]
> Indentation shows related commands like installations and ripped long commands.

What I mean is you're mixing spaces and tabs even at the first level of indentation.

**Comment by TriplEight** [comment]
oh noes, will fix it right away.

**Pull request merged**
