### PR TITLE
Update diener version

### PR DESCRIPTION
**Pull request by joao-paulo-parity**
See https://github.com/paritytech/pipeline-scripts/issues/97#issuecomment-1420642980 for context.

Tested through https://github.com/paritytech/substrate/pull/13324 (see https://github.com/paritytech/scripts/pull/506#issuecomment-1420694711).

closes https://github.com/paritytech/pipeline-scripts/issues/97

### CODE REVIEW

**Comment by joao-paulo-parity** [comment]
Per https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2360001 and https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2360000 from https://github.com/paritytech/substrate/pull/13324 the patching seems to be happening without issues. The job is failing due to some code-related problem unrelated to `diener`.

**Comment by joao-paulo-parity** [comment]
Per https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2360018 (note [line 127](https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2360018#L127)) and https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2360019 (note [line 127](https://gitlab.parity.io/parity/mirrors/substrate/-/jobs/2360019#L127)) from https://github.com/paritytech/substrate/pull/13324, the patching seems to be happening without issues. The job is failing due to some code-related problem unrelated to `diener`.

**Comment by mordamax** [comment]
@joao-paulo-parity sorry by the provided links the jobs are failed
Could you please also provide an evidence of -v PATCH_polkadot=xxx or cumulus case?
thanks

**Comment by joao-paulo-parity** [comment]
> sorry by the provided links the jobs are failed

Yes, I'm aware. I mentioned that at the end of https://github.com/paritytech/scripts/pull/506#issuecomment-1420694711.

> -v PATCH_polkadot=xxx

Why does this matter?

**Comment by mordamax** [comment]
> Yes, I'm aware. I mentioned that at the end of [#506 (comment)](https://github.com/paritytech/scripts/pull/506#issuecomment-1420694711).
But it's not clear wether it was a wrong patch problem or a code, ideally that should succeed to confirm the evidence of work

> > -v PATCH_polkadot=xxx
> Why does this matter?
The last time we updated a diener, it was working with a simple companion cases, but i didn't with a PATCH_repo. That's why I think it's important to test and make sure

> Why would the flow with a companion PR behave differently w.r.t. `diener`?
Who knows, better know & make sure before roll-out than after

**Comment by joao-paulo-parity** [comment]
> But it's not clear wether it was a wrong patch problem or a code, ideally that should succeed to confirm the evidence of work

It was explictly stated that "The job is failing due to some code-related problem unrelated to `diener`", but alright... I suppose it makes sense to only trust that if the job is actually passing.

> The last time we updated a diener, it was working with a simple companion cases, but i didn't with a PATCH_repo. That's why I think it's important to test and make sure

There's no usage of `PATCH_something` in the companion scripts. Unless I'm missing something? IIRC it was the `try-runtime-bot` script that had something like that.

---

Anyways, although I don't think that those extra tests are useful (there should be a standard testing procedure specifically for `diener` changes depending on what has changed about it), I'll report back here once I have evidence of

- "No companions" case passing
- "Polkadot companion" case passing
- "Cumulus companion" case passing
- "Polkadot + Cumulus companion" case passing

**Review by chevdor — APPROVED** [review]

**Review by sergejparity — APPROVED** [review]

**Review by mordamax — CHANGES_REQUESTED** [review]
Thanks, looking forward for results!

**Comment by altaua** [comment]
Merging per https://github.com/paritytech/ci_cd/issues/773#issuecomment-1497741491

**Pull request merged**
